# Evaluated Tools

| Tool Name | Category | Description | Status | Deployment | Technical Level | Documentation | Overall Rating | Last Tested |
|----------|-----------|-------------|---------|------------|-----------------|---------------|----------------|-------------|
| [Tor Browser](https://www.torproject.org/) | Browser | Tor Browser is a free, privacy-focused web browser that uses the Tor network to encrypt traffic and protect users' anonymity online. | Active | A service with a local client that’s hosted by a third party - You install a client on your device, but it connects to and depends on a remote server (Tor Browser is a software that runs locally on a computer but connects to the Tor network to surf the web). | Intermediate | [Details](categories/browser/tor-browser.md) | ⭐⭐⭐⭐⯪ (4.51) | 2025-04-02 |
| [Magic Wormhole](https://github.com/magic-wormhole/magic-wormhole) | File Transfer | Magic wormhole provides a library & a command line so users can send arbitrary sized files and directories from one computer to another. | Active | A service with a local client that’s hosted by a third party - You install a client on your device, but it connects to and depends on a remote server. | Intermediate | [Details](categories/file-transfer/magic-wormhole.md) | ⭐⭐⭐⭐☆ (4.15) | 2025-04-02 |
| [Send](https://github.com/timvisee/send) | File Transfer | Send enables secure, end-to-end encrypted file transfers, ensuring user privacy and anonymity. | Active | A service with a local client that’s hosted by a third party and A service that is hosted by a third party but can also be self-hosted | Beginner | [Details](categories/file-transfer/send.md) | ⭐⭐⭐⯪☆ (3.62) | 2025-03-27 |
| [Croc](https://github.com/schollz/croc) | File Transfer | Croc enables secure, end-to-end encrypted file transfers over the internet, ensuring user privacy and anonymity. | Active | A service that is hosted by a third party but can also be self-hosted. | Intermediate | [Details](categories/file-transfer/croc.md) | ⭐⭐⭐⯪☆ (3.98) | 2025-04-07 |
| [Bitwarden](https://bitwarden.com/) | Password Management | Bitwarden is a secure password manager that helps individuals and organizations store, manage, and share passwords and sensitive data safely. It uses end-to-end encryption to protect your information. | Active | A service that is hosted by a third party but can also be self-hosted. | Beginner | [Details](categories/password-management/bitwarden.md) | ⭐⭐⭐⭐⯪ (4.69) | 2025-03-27 |
| [PrivateBin](https://privatebin.info/) | PasteBins | PrivateBin is a minimalist, open source online pastebin where the server has zero knowledge of pasted data. | Active | PrivateBin is a self-hosted web application, meaning you deploy it on your own server. It runs entirely on the backend you control, with all encryption and decryption handled in the user’s browser, ensuring zero-knowledge privacy (It is self hostable but there is a public instance available to use). | Beginner | [Details](categories/pastebins/privatebin.md) | ⭐⭐⭐⭐☆ (4.18) | 2025-04-16 |
| [ThunderBird](https://www.thunderbird.net/en-US/) | Email Clients | Thunderbird is an open-source email application developed by Mozilla for managing multiple emails accounts with strong privacy, PGP encryption, OAuth2 support, and add-on extensibility. | Active | Thunderbird is a standalone, open-source desktop email client that is deployed locally on a user’s device. It is installed directly onto OS systems, where it manages and syncs emails, contacts, and calendars through IMAP, POP3, and other email protocols. The tool does not require a server for basic functionality but supports integration with external email services for sending and receiving messages (Thunderbird application is a standalone software but email data is located on the remote email server---IMAP or POP3). | Intermediate | [Details](categories/email-clients/thunderbird.md) | ⭐⭐⭐⭐⯪ (4.29) | 2025-04-23 |
| [VeraCrypt](https://www.veracrypt.fr/en/Home.html) | Encryption | VeraCrypt is a free, open-source disk encryption software that uses strong encryption techniques to protect individual files, folders, and whole drives. | Active | A standalone software - Runs entirely locally (e.g., runs on computer and doesn’t depend on external server). | Intermediate | [Details](categories/encryption/veracrypt.md) | ⭐⭐⭐⭐⯪ (4.75) | 2025-04-22 |
| [Signal](https://signal.org/) | Messaging | Signal is a secure messaging app designed to provide end-to-end encrypted communication, allowing users to send messages, make voice and video calls, and share files while maintaining privacy and security. | Active | A service with a local client that’s hosted by a third party - You install a client on your device, but it connects to and depends on a remote server (e.g., install app (client), but servers handle message relaying, etc.). | Beginner | [Details](categories/messaging/signal.md) | ⭐⭐⭐⭐⯪ (4.97) | 2025-03-27 |
| [LanguageTool](https://languagetool.org/) | Language Tools | LanguageTool is an open-source AI writing assistant that detects grammar, spelling, and style errors in multiple languages to improve writing. | Active | A standalone software – Runs entirely locally: If you download and install the LanguageTool desktop application or set up the offline version, it runs entirely on your computer without sending data to external servers. A locally hosted service with separate server and client component: You can also self-host LanguageTool by setting up the backend (server) and using browser extensions or other clients that connect to it. This gives you full control over your data while keeping the tool’s features. A service with a local client that’s hosted by a third party: You can install a browser extension, add-on, or use the web interface (the local client). These clients connect to LanguageTool’s remote servers, which handle grammar checking and processing. User text is sent to their servers for analysis unless you use a self-hosted or offline version. | Beginner | [Details](categories/language-tools/languagetool.md) | ⭐⭐⭐⯪☆ (3.46) | 2025-04-29 |
| [Notesnook](https://notesnook.com/) | Notebooks | Note-taking app that offers end-to-end encryption and designed to replace mainstream apps without compromising user privacy. | Active | A service with a local client that’s hosted by a third party - You install a client on your device, but it connects to and depends on a remote server. Can also be self-hosted. | Beginner | [Details](categories/notebooks/notesnook.md) | ⭐⭐⭐⭐⯪ (4.29) | 2025-04-21 |
| [Proton VPN](https://protonvpn.com/) | VPN Services | Provides secure and private internet browsing by encrypting user traffic and masking their IP address, offering enhanced online privacy and anonymity. | Active | A service with a local client that’s hosted by a third party - You install a client on your device, but it connects to and depends on a remote server. | Beginner | [Details](categories/vpn-services/proton-vpn.md) | ⭐⭐⭐⭐⯪ (4.73) | 2025-04-15 |
| [MAT2](https://github.com/jvoisin/mat2) | Data & Metadata Redaction | Mat2 (Metadata Anonymization Toolkit) is designed to remove metadata from files and documents to protect users' privacy. It strips metadata such as author names, software version, file history, location, and other personal information that can be embedded in files. | Active | A standalone software - Runs entirely locally (e.g., runs on computer and doesn’t depend on external server) | Intermediate | [Details](categories/data-&-metadata-redaction/mat2.md) | ⭐⭐⭐⯪☆ (3.83) | 2025-04-29 |
| [Ollama](https://ollama.com/) | AI Chat | Run large language models locally on personal computers for private, offline AI assistance. | Active | A standalone software - Runs entirely locally (e.g., runs on computer and doesn't depend on external server) | Intermediate | [Details](categories/ai-chat/ollama.md) | ⭐⭐⭐⭐☆ (4.05) | 2025-05-06 |
| [Cryptomator](https://cryptomator.org/) | Encryption | Designed to provide client-side encryption for files stored in the cloud | Active | A standalone software - Runs entirely locally (e.g., runs on computer and doesn't depend on external server) | Beginner | [Details](categories/encryption/cryptomator.md) | ⭐⭐⭐⭐⯪ (4.34) | 2025-04-22 |
| [Quiet](https://tryquiet.org/) | Messaging | A secure messaging platform that operates over Tor onion services, providing end-to-end encryption and decentralized communication without relying on central servers. | Active | A standalone software - Runs entirely locally (e.g., runs on computer and doesn't depend on external server) | Beginner | [Details](categories/messaging/quiet.md) | ⭐⭐⭐⯪☆ (3.26) | 2025-04-23 |
| [LibreOffice](https://www.libreoffice.org/) | Office Suite | An open source office suite designed for document creation, editing and collaboration, providing offline functionality and comprehensive document management capabilities. | Active | A standalone software - Runs entirely locally (e.g., runs on computer and doesn't depend on external server) | Beginner | [Details](categories/office-suite/libreoffice.md) | ⭐⭐⭐⯪☆ (3.94) | 2025-04-23 |
| [ONLYOFFICE](https://www.onlyoffice.com/) | Office Suite | An open source office suite designed for document creation, editing and collaboration, including comprehensive document management through Docs and DocSpace platforms. | Active | A service that is hosted by a third party but can also be self-hosted | Beginner | [Details](categories/office-suite/onlyoffice.md) | ⭐⭐⭐⭐☆ (4.21) | 2025-04-17 |
| [Standard Notes](https://standardnotes.com/) | Notebooks | Free, secure note-taking app with end-to-end encryption and privacy features, offering offline functionality and minimal data collection. | Active | A service that is hosted by a third party but can also be self-hosted | Beginner | [Details](categories/notebooks/standard-notes.md) | ⭐⭐⭐⯪☆ (3.61) | 2025-04-03 |
| [DuckDuckGo](https://duckduckgo.com/) | Privacy Search Engine | A privacy-focused search engine that doesn't track users, log personal data, or personalize search results based on prior activity, offering tracker blocking and anonymous browsing capabilities. | Active | A service with a local client that's hosted by a third party - You install a client on your device, but it connects to and depends on a remote server | Beginner | [Details](categories/privacy-search-engine/duckduckgo.md) | ⭐⭐⭐⭐⯪ (4.35) | 2025-04-17 |
| [AdGuard](https://adguard.com/) | Ad-Tracker Blocking | A comprehensive ad-blocking and privacy protection extension that blocks ads, online tracking, and enhances privacy across multiple browsers and platforms. | Active | A standalone software - Runs entirely locally (e.g., runs on computer and doesn't depend on external server) | Beginner | [Details](categories/ad-tracker-blocking/adguard.md) | ⭐⭐⭐⭐⯪ (4.56) | 2025-03-30 |
